commitlint-branch:
  stage: test
  variables:
    # We need enough history to find a common ancestor with origin/main.
    # GIT_DEPTH: 1000
  before_script:
    - apk add --update git bash
  script:
    - devtools/commitlint-branch/bin/build.sh
    - devtools/commitlint-branch/bin/run.sh
