GET http://localhost:10350/version

###
GET http://localhost:10350/guests

###
GET http://localhost:10350/guests/123-23

###
DELETE http://localhost:10350/guests/123-23

###
POST http://localhost:10350/guests HTTP/1.1
content-type: application/json

{
  "wneID": "123-23",
  "residency": "commuter",
  "grad_year": 2023,
  "grad": "UG",
  "date": "04-12-2023"
}

###
POST http://localhost:10350/guests HTTP/1.1
content-type: application/json

{
  "wneID": "246-23",
  "residency": "resident",
  "grad_year": 2024,
  "grad": "UG",
  "date": "04-15-2023"
}

###
PUT http://localhost:10350/guests/246-23 HTTP/1.1
content-type: application/json

{
  "wneID": "246-23",
  "residency": "resident",
  "grad_year": 2024,
  "grad": "G",
  "date": "04-15-2023"
}

###
GET http://localhost:10350/visits

###
GET http://localhost:10350/visits/04-12-2023+04-26-2023

###
POST http://localhost:10350/visits HTTP/1.1
content-type: application/json

{
  "wneID": "123-23",
  "date": "04-14-2023"
}

###
POST http://localhost:10350/visits HTTP/1.1
content-type: application/json

{
  "wneID": "246-23",
  "date": "04-26-2023"
}
