GET http://localhost:10350/version

###
GET http://localhost:10350/guests

###
GET http://localhost:10350/guests/1234567

###
GET http://localhost:10350/guests?resident=true

###
DELETE http://localhost:10350/guests/1234567

###
POST http://localhost:10350/guests HTTP/1.1
content-type: application/json

{
  "wsuID": "1234567",
  "resident": true,
  "zipCode": "01602",
  "unemployment": false,
  "assistance": {
    "socSec": false,
    "TANF": false,
    "finAid": false,
    "other": false,
    "SNAP": false,
    "WIC": false,
    "breakfast": false,
    "lunch": false,
    "SFSP": false
  },
  "guestAge": 42, 
  "numberInHousehold": 4
}

###
POST http://localhost:10350/guests HTTP/1.1
content-type: application/json

{
  "wsuID": "1234568",
  "resident": false,
  "zipCode": "01603",
  "unemployment": false,
  "assistance": {
    "socSec": false,
    "TANF": false,
    "finAid": false,
    "other": false,
    "SNAP": false,
    "WIC": false,
    "breakfast": false,
    "lunch": false,
    "SFSP": false
  },
  "guestAge": 42, 
  "numberInHousehold": 4
}

###
PUT http://localhost:10350/guests/1234561 HTTP/1.1
content-type: application/json

{
  "wsuID": "1234561",
  "resident": true,
  "zipCode": "01602",
  "unemployment": false,
  "assistance": {
    "socSec": false,
    "TANF": false,
    "finAid": false,
    "other": false,
    "SNAP": false,
    "WIC": false,
    "breakfast": false,
    "lunch": false,
    "SFSP": false
  },
  "guestAge": 42, 
  "numberInHousehold": 5
}
