image: docker:20.10.16
services:
  - docker:20.10.16-dind

stages:
  - lint
  - build
  - test
  - deliver

include:
  - '/tools/lint-shell-scripts/gitlab-ci.yml'
  - '/tools/lint-markdown-links/gitlab-ci.yml'
  - '/tools/lint-dockerfiles/gitlab-ci.yml'
  - '/tools/lint-markdown-files/gitlab-ci.yml'
  - '/tools/lint-js-json-vue-files/gitlab-ci.yml'
  - '/tools/lint-package-json/gitlab-ci.yml'
  - '/tools/lint-commits-on-branch/gitlab-ci.yml'

##################################################################
# Below is the original build and delivery mechanism. Delete after
# itegrating into the new systems.

# variables:
#   CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
#   CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

# build:
#   stage: build
#   before_script:
#     - apk add docker-compose
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   script:
#     - docker-compose build --pull backend
#     - docker tag backend $CONTAINER_TEST_IMAGE
#     - docker push $CONTAINER_TEST_IMAGE

# release:
#   stage: deliver
#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#     - docker push $CONTAINER_RELEASE_IMAGE
