GET http://localhost:10350/guest/list

###
GET http://localhost:10350/guest/1234567

###
//Trigger this PUT the first time will create new student with ID: 1234567, the second time it will update the student data
PUT http://localhost:10350/guest/1234567 HTTP/1.1
content-type: application/json

{
  "studentID": "1234567",
  "resident": true,
  "zipCode": "01610",
  "unemployment": false,
  "assistance": {
    "socSec": false,
    "TANF": false,
    "finAid": false,
    "other": false,
    "SNAP": false,
    "WIC": false,
    "breakfast": false,
    "lunch": false,
    "SFSP": false
  },
  "studentAge": 42, 
  "numberInHousehold": 4
}

###
PUT http://localhost:10350/guest/1234568 HTTP/1.1
content-type: application/json

{
  "studentID": "1234568",
  "resident": true,
  "zipCode": "01603",
  "unemployment": false,
  "assistance": {
    "socSec": false,
    "TANF": false,
    "finAid": false,
    "other": false,
    "SNAP": false,
    "WIC": false,
    "breakfast": false,
    "lunch": false,
    "SFSP": false
  },
  "studentAge": 42, 
  "numberInHousehold": 4
}