version: "3.3"
services:

  backend-server:
    image: backend-server
    build: .
    ports:
      - 10350:10350
    environment:
      BASE_URL: http://localhost:10350/
      MONGO_URI: mongodb://backend-database
    networks:
      - backend-network
    depends_on:
      - backend-database

  backend-database:
    image: mongo:4
    networks:
      - backend-network

networks:
  backend-network: