lint-commits-on-branch:
  stage: lint
  variables:
    # We need enough history to find a common ancestor with origin/main.
    # GIT_DEPTH: 1000
  before_script:
    - apk add --update git bash
  script:
    - tools/lint-commits-on-branch/commands/build.sh
    - tools/lint-commits-on-branch/commands/run.sh
